/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gologolo;

/**
 *
 * @author akillhalimi
 */
public enum GoLogoPropertyType {
     GOLO_PANE,
     GOLO_BAR,
    // ADDING LOGO
    GOLO_USER_TOOLS_PANE,
    GOLO_TOOL_PANE,
    GOLO_BUTTON_PANE,
    GOLO_ADD_TEXT_BUTTON,
    GOLO_ADD_IMAGE_BUTTON,
    GOLO_ADD_SQUARE_BUTTON,
    GOLO_ADD_CIRCLE_BUTTON,
    GOLO_ADD_TRIANGLE_BUTTON,
    GOLO_ADD_DELETE_BUTTON,
    
    //CHOOSING FONT 
    GOLO_TEXT_PANE,
    GOLO_B_TEXT_PANE,
    GOLO_B_B_PANE,
    LIST,
    SIZE,
    DEFAULT_SCRIPT,
    DEFAULT_SIZE,
    GOLO_FONT_CHOICE,
    GOLO_SIZE_CHOICE,
    GOLO_FONT_SIZE_BUTTON,
    GOLO_BOLD_TEXT_BUTTON,
    GOLO_ITALICIS_TEXT_BUTTON,
    GOLO_DECREASE_FONT_BUTTON,
    GOLO_INCREASE_FONT_BUTTON,
    GOLO_UNDERLINE_TEXT_BUTTON,
    
    //EDITING FONT
    GOLO_EDIT_TEXT_PANE,
    GOLO_BORDER_PANE,
    GOLO_BORDER_THICKNESS,
    BORDER_THICKNESS_SLIDER,
    GOLOR_COLOR_LABEL,
    GOLO_THICKNESS_BOX,
    GOLO_COLOR_BOX,
    GOLO_RADIUS_LABEL,
    GOLO_BORDER_RADIUS_BOX,
    
    //COLOR GRADIENT
    GOLO_GRADIENT_PANE,
    GOLO_GRADIENT_LABEL,
    GOLO_ANGLE_BOX,
    GOLO_FOCUS_LABEL,
    GOLO_FOCUS_LABEL_DIST,
    GOLO_FOCUS_DIST_SLIDER,
    GOLO_CENTER_LABEL_X,
    GOLO_CENTER_X_SLIDER,
    GOLO_CENTER_LABEL_Y,
    GOLO_CENTER_Y_SLIDER,
    GOLO_COLOR_RADIUS_SLIDER,
    GOLO_COLOR_RADIUS_LABEL,
    GOLO_CYCLE_METHOD,
    
    CYCLE,
    DEFAULT_CYCLE,
    GOLO_STOP_0_COLOR,
    GOLO_STOP_1_COLOR,
    GOLO_TYPE_TEXT,
    GOLO_DISTANCE_BOX,
    GOLO_X_CENTER_BOX,
    GOLO_Y_CENTER_BOX,
    GOLO_GRADIENT_RADIUS_BOX,
    GOLO_CYCLE_BOX,
    GOLO_COLOR_STOP_0_PICKER,
    GOLO_COLOR_STOP_1_PICKER,

    // FOOLPROOF SETTINGS
    GOLO_FOOLPROOF_SETTINGS,
    
    //VIEWING
    GOLO_DATA_PANE,
    GOLO_ORDER_COLUMN,
    GOLO_NAME_COLUMN,
    GOLO_TYPE_COLUMN,
    GOLO_BUTTON_DATA_PANE,
    GOLO_UP_BUTTON,
    GOLO_DOWN_BUTTON,
    GOLO_EDIT_BUTTON,
    //center where the image will show
    GOLO_IMAGE_PANE,
    GOLO_IMAGE_CANVAS,
    
    
    // DIALOG CONTROLS
    GOLO_ITEM_DIALOG_HEADER,
    GOLO_ITEM_DIALOG_ADD_HEADER_TEXT,
    GOLO_ITEM_DIALOG_EDIT_HEADER_TEXT,
    
    // THIS IS THE EXPORT TEMPLATE FILE NAME
    GOLO_EXPORT_TEMPLATE_FILE_NAME,
    
    
    GOLO_HEADER_ADD_TXT,
    GOLO_TEXT_LABEL,
    GOLO_TEXT_FEILD,
    GOLO_ITEM_DIALOG_OK_BUTTON,
    GOLO_ITEM_DIALOG_CANCEL_BUTTON,
    GOLO_ITEM_DIALOG_BUTTON_PANE,
    GOLO_ITEM_NAME,
    GOLO_ITEM_NAME_PANE,
    GOLO_NAME_TEXT_FEILD,
}
